/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package blackjack2;

/**
 *
 * @author Tiago
 */
public class NameFrame extends javax.swing.JFrame {

    private int countPlayers;
    private Game game;
    private GameFrame gameFrame;

    public NameFrame(Game game, int n) {
        countPlayers = n;
        this.game = game;
        initComponents();
        if (n < 3) {
            tfP4.setVisible(false);
            lbP4.setVisible(false);
            if (n < 2) {
                tfP3.setVisible(false);
                lbP3.setVisible(false);
                if (n < 1) {
                    tfP2.setVisible(false);
                    lbP2.setVisible(false);
                }
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgDificult = new javax.swing.ButtonGroup();
        lpName = new javax.swing.JLayeredPane();
        lbP1 = new javax.swing.JLabel();
        lbP2 = new javax.swing.JLabel();
        lbP3 = new javax.swing.JLabel();
        lbP4 = new javax.swing.JLabel();
        tfP1 = new javax.swing.JTextField();
        tfP2 = new javax.swing.JTextField();
        tfP3 = new javax.swing.JTextField();
        tfP4 = new javax.swing.JTextField();
        btOk = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(481, 417));
        setMinimumSize(new java.awt.Dimension(481, 417));
        setPreferredSize(new java.awt.Dimension(481, 417));
        setResizable(false);
        setSize(new java.awt.Dimension(481, 417));
        getContentPane().setLayout(null);

        lbP1.setText("Player 1");

        lbP2.setText("Player 2");

        lbP3.setText("Player 3");

        lbP4.setText("Player 4");

        tfP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfP1ActionPerformed(evt);
            }
        });

        btOk.setText("OK");
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lpNameLayout = new javax.swing.GroupLayout(lpName);
        lpName.setLayout(lpNameLayout);
        lpNameLayout.setHorizontalGroup(
            lpNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lpNameLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(lpNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(lpNameLayout.createSequentialGroup()
                        .addComponent(lbP3)
                        .addGap(18, 18, 18)
                        .addComponent(tfP3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(lpNameLayout.createSequentialGroup()
                        .addComponent(lbP2)
                        .addGap(18, 18, 18)
                        .addComponent(tfP2))
                    .addGroup(lpNameLayout.createSequentialGroup()
                        .addComponent(lbP1)
                        .addGap(18, 18, 18)
                        .addComponent(tfP1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(lpNameLayout.createSequentialGroup()
                        .addComponent(lbP4)
                        .addGap(18, 18, 18)
                        .addGroup(lpNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfP4)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lpNameLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btOk, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)))))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        lpNameLayout.setVerticalGroup(
            lpNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lpNameLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(lpNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbP1)
                    .addComponent(tfP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(lpNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbP2)
                    .addComponent(tfP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(lpNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbP3)
                    .addComponent(tfP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(lpNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbP4)
                    .addComponent(tfP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btOk, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        lpName.setLayer(lbP1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpName.setLayer(lbP2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpName.setLayer(lbP3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpName.setLayer(lbP4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpName.setLayer(tfP1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpName.setLayer(tfP2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpName.setLayer(tfP3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpName.setLayer(tfP4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpName.setLayer(btOk, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(lpName);
        lpName.setBounds(0, 0, 480, 420);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjack2/images/cards.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 480, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfP1ActionPerformed

    private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
        ((Player) game.getPlayers().get(0)).setName(tfP1.getText());
        if (countPlayers > 0) {
            ((Player) game.getPlayers().get(1)).setName(tfP2.getText());
            if (countPlayers > 1) {
                ((Player) game.getPlayers().get(2)).setName(tfP3.getText());
                if (countPlayers > 2) {
                    ((Player) game.getPlayers().get(3)).setName(tfP4.getText());
                }
            }
        }
        gameFrame = new GameFrame(game);
        gameFrame.setVisible(true);
        gameFrame.initGame();
        this.setVisible(false);
        //passar os nomes dos playes pro gameFrame e dificuldade
    }//GEN-LAST:event_btOkActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgDificult;
    private javax.swing.JButton btOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbP1;
    private javax.swing.JLabel lbP2;
    private javax.swing.JLabel lbP3;
    private javax.swing.JLabel lbP4;
    private javax.swing.JLayeredPane lpName;
    private javax.swing.JTextField tfP1;
    private javax.swing.JTextField tfP2;
    private javax.swing.JTextField tfP3;
    private javax.swing.JTextField tfP4;
    // End of variables declaration//GEN-END:variables
}
